### ISSUE TITLE
Extract typedefs to primitives

### ISSUE THREAD

**Issue by clangenb** [integritee-network/pallets#7]
In the substraTEE-worker we have to import the whole runtime to merely access some types. We can also redefine them in the worker, but it would be best to have them in a separate crate.

**Comment by clangenb** [comment]
While doing this, we can move the `Enclave`-builder implementation from `pallet-teerex` to either `test-utils` or primitives too.

**Comment by haerdib** [comment]
This one has been closesd but I'd like to question it now: What's the use case of having a separate primitives crate containing all primitives compared to a primitives crate inside each pallet?

I.e. primitives/teerex vs teerex/primitives?

Because I don't see the use case of the first one. The use case of the second one would be in case someone would like to extract the teerex pallet only, only one folder (teerex) would need to be extracted. And the primitives can still be pulled separately.

**Comment by clangenb** [comment]
I see your point. I think it depends on the use-case. In Encointer, all the pallets are closely entangled, so it's convenient for them to be in one place. They are even in a single crate there. I don't know about the pallet's introduced here.

However, it is not the goal that projects have a copy of the pallet-teerex. Ours should hopefully fit all purposes. Has this not been the case?

**Comment by haerdib** [comment]
Polkadex has forked the pallet, though they didn't introduce new functionalities. I don't know about other forks, but I guess there always will be special use cases that might need something extraordinary. 

I don't think our pallets are that closely entangled.

**Comment by clangenb** [comment]
Regardless of potential pallet forks, I agree that your design makes more sense. However, this should be in a follow-up issue: #18
